### PR TITLE
made the regex expect a major version number after [vV]

### PR DESCRIPTION
**Pull request by Pshy0**
Fix for #1086

This updates the regex from
`^[vV]?((\.?[0-9]+)+)[a-z]?(-?[a-z]+[0-9]*)?$`
to
`^[vV]?[0-9]+(\.[0-9]+)*[a-z]?(-?[a-z]+[0-9]*)?$`

This way, a number is required after "V" or "v" for the regex to match (major number can no longer be empty).

### CODE REVIEW

**Comment by MCOfficer** [comment]
So here's what i'm thinking: Currently the regex in question is `^[vV]?((\.?[0-9]+)+)` - ignoring any pre- and suffixes. `v.10.0.1` matches that (resulting in `.10.0.1`), which is then split by `.`, to produce a list of integers. Only that the first item in that list is empty, since the leading dot is part of the match.

Wouldn't it be better to either strip the leading `.` in python, or extend the regex from
`^[vV]?((\.?[0-9]+)+)`
to
`^[vV]?\.?((\.?[0-9]+)+)`
?

**Comment by Pshy0** [comment]
Oh indeed you need the capturing groups to get the version...

Getting the version numbers with the dots and then splitting it would be simpler, but if you want to support all version formats you need an algorithm that take the whole tag into account, like `sort --version-sort` does.

In all cases I think `v.10.0.1` should not even be matched, you don't know in that case if it was meant to be `v0.10.0.1` or `v10.0.1`.

**Comment by Pshy0** [comment]
For the sort, `distutils.version` as a `StrictVersion` comparison function that does just that.

**Comment by Pshy0** [comment]
image

**Comment by Pshy0** [comment]
Oh it' s deprecated, im checking the new thing
image

**Comment by MCOfficer** [comment]
Also run autoupdate for the manifest folder once, because the distutils way doesn't seem to like some of these:
```
$ python .\scripts\autoupdate.py .\manifests\

[...]

Running autoupdate for .\manifests\Better Vanilla Hai.yaml
['0.9.2', 'v0.9', 'v0.9.1']
Traceback (most recent call last):
  File "C:\Users\MCO\Code\endless-sky-plugins\scripts\autoupdate.py", line 115, in <module>
    update(file)
  File "C:\Users\MCO\Code\endless-sky-plugins\scripts\autoupdate.py", line 93, in update
    latest_version = get_latest_version(au_type, au_url, au_branch)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MCO\Code\endless-sky-plugins\scripts\autoupdate.py", line 73, in get_latest_version
    return get_latest_versioned_tag_from_refs(refs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MCO\Code\endless-sky-plugins\scripts\autoupdate.py", line 49, in get_latest_versioned_tag_from_refs
    tags.sort(key=distutils.version.LooseVersion)
  File "C:\Users\MCO\Code\endless-sky-plugins\venv\Lib\site-packages\setuptools\_distutils\version.py", line 72, in __lt__
    c = self._cmp(other)
        ^^^^^^^^^^^^^^^^
  File "C:\Users\MCO\Code\endless-sky-plugins\venv\Lib\site-packages\setuptools\_distutils\version.py", line 351, in _cmp
    if self.version < other.version:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by Pshy0** [comment]
> Wouldn't it be better to either strip the leading `.` in python, or extend the regex from `^[vV]?((\.?[0-9]+)+)` to `^[vV]?\.?((\.?[0-9]+)+)` ?

In the case of the plugin, this would make you consider the version to be `10.0.1` while it should be `0.10.0.1`
image

This could result in the plugin stopping updating because this errorneous tag would always be the latest.

Another example:
image

**Comment by Pshy0** [comment]
This is caused by mixing tags beginning or not with "v"

**Comment by MCOfficer** [comment]
Is this good to go, or do you still want to migrate away from distutils?

**Comment by Pshy0** [comment]
> Is this good to go, or do you still want to migrate away from distutils?

There is version numbers that the deprecated `distutils.version` accepts that the recommended and non-deprecated `packaging.version` does not.

Alternatively, `pkg_resources.parse_version` [is supposed to accept all version numbers](https://peps.python.org/pep-0386/#setuptools), but when I test it, it returns the same errors than `packaging.version`:
image

Apparently, they broke backward compatibility in new versions of python since their own examples does not even work
image

There is plugins that this will cause problems with:
image

**Comment by MCOfficer** [comment]
@mathwhiz1212 be aware that v.10.0.1a is now no longer considered latest. Please approve #1094

**Comment by mathwhiz1212** [comment]
> @mathwhiz1212 be aware that v.10.0.1a is now no longer considered latest. Please approve #1094, or advise how to change your manifest

That version number was a typo. I created a new tag with the correct v0.10.1a version. Do you need anything else from me?

**Comment by MCOfficer** [comment]
> > @mathwhiz1212 be aware that v.10.0.1a is now no longer considered latest. Please approve #1094, or advise how to change your manifest
> 
> That version number was a typo. I created a new tag with the correct v0.10.1a version. Do you need anything else from me?

nope, that was all.

**Pull request merged**
